// The base `cloudflare:test` module (env, SELF, etc.) is declared in the
// package's `/types` entry — the bare package reference resolves the pool types
// instead, which don't declare the module — so reference the types entry here.
/// <reference types="@cloudflare/vitest-pool-workers/types" />
import { type Env } from '../src/types.ts';

declare module 'cloudflare:test' {
  // The bindings available as `env` in tests mirror the Worker's Env.
  interface ProvidedEnv extends Env {}
}

// In this pool version `env` from 'cloudflare:test' is typed `Cloudflare.Env`
// (the global ambient env, normally generated by `wrangler types`). Augment it
// with our bindings so the typed `env` matches the Worker's Env.
declare global {
  namespace Cloudflare {
    // Keep this binding list in sync with `Env` in src/types.ts. This pool
    // version requires the explicit members here rather than `extends Env`.
    interface Env {
      DB: D1Database;
      OAUTH_KV: KVNamespace;
      ALLOWED_ORIGIN: string;
      GOOGLE_CLIENT_ID?: string;
      GOOGLE_CLIENT_SECRET?: string;
      COOKIE_ENCRYPTION_KEY?: string;
    }
  }
}
